apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-otel
  spec:
    mode: sidecar

    config:
      receivers:
        otlp:
          protocols:
            grpc:
            http:

      processors:
        batch:

      exporters:
        otlp:
          endpoint: datadog-agent.datadog.svc.cluster.local:4317
          tls:
            insecure: true

      service:
        pipelines:
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp]