name: 'Deploy REST API'

on:
  workflow_dispatch:
    inputs:
      app_version:
        description: 'App Version ex:1.0.0'
        required: true
        default: 1.0.0
      skip_docker:
        description: 'Skip docker build'
        required: true
        default: 'false'

permissions:
  contents: read

jobs:
  docker:
    name: 'Build Docker'
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      if: ${{ github.event.inputs.skip_docker  == 'false' }}
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker
      if: ${{ github.event.inputs.skip_docker  == 'false' }}
      uses: docker/build-push-action@v6
      with:
        push: false
        context: ./app
        file: ./app/Dockerfile
        platforms: linux/amd64
        tags: rest-api-flask:${{ github.event.inputs.app_version }}
        outputs: type=docker
    
    - name: Push to ECR
      if: ${{ github.event.inputs.skip_docker  == 'false' }}
      id: ecr
      uses: jwalton/gh-ecr-push@v2
      with:
        access-key-id:  ${{ secrets.AWS_ACCESS_KEY }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-east-1
        image: rest-api-flask:${{ github.event.inputs.app_version }}
    
    

