# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the "main" branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: 'Infra'

on:
  push:
  pull_request:
  
  workflow_dispatch:
    inputs:
      terraform_destroy:
        description: 'Destroy infra'
        required: true
        default: 'false'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout  
      uses: actions/checkout@v4

    - name: Configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.2
      
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      working-directory: ./infra

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: |
        export TF_VAR_agent_ip=$(curl ifconfig.me; echo)
        terraform plan -input=false
      working-directory: ./infra
      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      run: |
        export TF_VAR_agent_ip=$(curl ifconfig.me; echo)
        terraform apply -auto-approve -input=false
      working-directory: ./infra

    - name: Terraform Output
      run: |
        terraform output -raw kubeconfig > kubeconfig
        cat kubeconfig
        echo 'KUBE_CONFIG_DATA<<KUBECONFIG' >> $GITHUB_ENV
        echo $(cat ./kubeconfig | base64) >> $GITHUB_ENV
        echo 'KUBECONFIG' >> $GITHUB_ENV   
      working-directory: ./infra
    - name: Install argo
      uses: koslib/helm-eks-action@master
      env:
        KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
      with:
        command: |
          kubectl apply -k "https://github.com/ argoproj/argo-cd/manifests/crds?ref=v2.4.9"
          kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

    - name: Install datadog
      uses: koslib/helm-eks-action@master
      env:
        KUBE_CONFIG_DATA: ${{ env.KUBE_CONFIG_DATA }}
      with:
        command: |
          helm repo add datadog https://helm.datadoghq.com
          helm install datadog-operator datadog/datadog-operator
          kubectl create secret generic datadog-secret --from-literal api-key=ef159d812453f08f1c839b832ab6531d
          cat <<EOF | kubectl apply -f -
          kind: "DatadogAgent"
          apiVersion: "datadoghq.com/v2alpha1"
          metadata:
            name: "datadog"
          spec:
            global:
              site: "datadoghq.com"
              credentials:
                apiSecret:
                  secretName: "datadog-secret"
                  keyName: "api-key"
          EOF

    - name: Terraform Destroy
      if: ${{ github.event.inputs.terraform_destroy  == 'true' }}
      run: terraform destroy -auto-approve -input=false -var 
      working-directory: ./infra      
    
